### ISSUE TITLE
Special characters in M3U file can fail parsing

### ISSUE THREAD

**Issue by bgoncal** [omaralbeik/M3UKit#10]
http://bit.ly/022qseed breaks the parser, It contains a special character at the beginning which makes the code in file "PlaylistParser" to fail with error "ParsingError.invalidSource".

Would be possible to treat this case in the parser? Something like 
```
guard rawString.<remove-illegal-chars>.starts(with: filePrefix) else {
       throw ParsingError.invalidSource
 }
```

**Comment by omaralbeik** [comment]
@cpvbruno Sorry for my late response here, could you please send a new link for the example above

**Comment by bgoncal** [comment]
Hey, sorry the URL was not mine and I don't have a new one, the case was that at the beginning of that file there were some hidden characters in the string, so the comparison of filePrefix was always returning false... I believe we can ignore this for now, these files come in some many wrongly formatted cases that its difficult to keep it up, I wish VLC provided their logic of parsing things hahaha VLC App parser any possible file you give them
