### ISSUE TITLE
M3UKit cannot be installed by CocoaPods

### ISSUE THREAD

**Issue by FunnyerFeng** [omaralbeik/M3UKit#17]

**Comment by Sab3rRid3r** [comment]
Same here: 
pod install
Analyzing dependencies
Pre-downloading: `M3UKit` from `https://github.com/omaralbeik/M3UKit.git`, tag `0.8.0`
[!] Unable to find a specification for 'M3UKit'.

**Comment by omaralbeik** [comment]
Please try installing again using v0.8.1
